apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
     matchLabels:
        app: nginx
  replicas: 1
  template:
   metadata:
     labels:
       app: nginx
   spec:
     containers:
       - name: nginx
         image: nginx:alpine
         ports:
         - containerPort: 80
         volumeMounts:
           - name: nginx-cfg
             mountPath: /etc/nginx/conf.d/default.conf
             subPath: default.conf
     volumes:
       - name: nginx-cfg
         configMap:
           name: nginx-cfg
