apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: chatapp-cluster
  region: us-east-2

nodeGroups:
  - name: node-ing
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 80
