apiVersion: v1
kind: Secret
metadata:
    name: db-secret
type: Opaque
stringData:
  MYSQL_USER: chatapp
  MYSQL_DATABASE: chatapp
  MYSQL_PASSWORD: chatapp123
  MYSQL_ROOT_PASSWORD: password